// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/rgen.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// test
void test();
RcppExport SEXP rgen_test() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    test();
    return R_NilValue;
END_RCPP
}
